version: "3"

services:
  noddfcd:
    image: dfcio/dfc:latest
    command: /opt/dfcio/bin/noddfcd.sh --data-dir /opt/dfcio/bin/data-dir -e --http-alias=noddfcd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: noddfcd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - noddfc-data-volume:/opt/dfcio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kdfcd:
    image: dfcio/dfc:latest
    command: /opt/dfcio/bin/kdfcd --wallet-dir /opt/dfcio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kdfcd:8900 --http-alias=localhost:8900
    hostname: kdfcd
    links:
      - noddfcd
    volumes:
      - kdfcd-data-volume:/opt/dfcio/bin/data-dir
    stop_grace_period: 10m

volumes:
 noddfc-data-volume:
   external: true
 kdfcd-data-volume:
   external: true
